### ISSUE TITLE
Demo on mobile doesn’t display map

### ISSUE THREAD

**Issue by michaelromose** [MartinP460/react-denmark-map#52]
### Description

On iOS safari, map is not displayed at all

### Expected behavior

Using Safari on iOS latest, go to demo deployed on vercel.  See map. 

### Actual behaviour

Map is not displayed

### How to reproduce

4. See above

### Specifications

- Browser: [e.g. chrome, safari]
- `react-denmark-map` version: [e.g. 22]

**Comment by MartinP460** [comment]
Thank you for reporting this! We're aware of it and working on solving it ASAP.

**Comment by MartinP460** [comment]
The issue was that the SVG that renders the map requires explicit `width` and/or `height` attributes in some environments (.e.g. Safari) in order to render.

Thank you for reporting it again, it really means a lot!
